name: Update Lists

on:
  schedule:
    - cron: '0 */6 * * *'  # Каждые 6 часов
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download white list
        run: |
          TIMESTAMP=$(date +%s)
          curl -L "https://raw.githubusercontent.com/hxehex/russia-mobile-internet-whitelist/refs/heads/main/cidrwhitelist.txt?invalidateCache=${TIMESTAMP}" -o docs/data/white.lst
      
      - name: Download black list
        run: |
          TIMESTAMP=$(date +%s)
          curl -L "https://antifilter.download/list/allyouneed.lst?invalidateCache=${TIMESTAMP}" -o docs/data/black.lst
      
      - name: Update timestamp
        run: |
          date +%s > docs/data/update.time
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/data/white.lst docs/data/black.lst docs/data/update.time
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update lists - $(date -u +"%Y-%m-%d %H:%M:%S UTC")" && git push)
